
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: RailsProject_development


test:
  <<: *default
  database: RailsProject_test

production:
  <<: *default
  database: RailsProject_production
