
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: Savannah_development


test:
  <<: *default
  database: Savannah_test

production:
  <<: *default
  database: Savannah_production
